// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BuilderGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "6456e5fd-ccef-44a3-830f-731063a61ded";
        public const string Name = "Builder Generator";
        public const string Description = @"It generates a Builder Class from an Entity or Model Class";
        public const string Language = "en-US";
        public const string Version = "1.0.0.1";
        public const string Author = "Julio Robles";
        public const string Tags = "";
    }
}
