// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BuilderGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string BuilderGeneratorString = "6e722322-fd16-477a-8ae4-dfeb39e52cbb";
        public static Guid BuilderGenerator = new Guid(BuilderGeneratorString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int BuildMenuGroup = 0x0001;
        public const int BuildCommand = 0x0100;
    }
}