// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BuilderGeneratorExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string BuilderGeneratorExtensionString = "dd3443a0-9221-4e8c-91e5-0ef07b1dd083";
        public static Guid BuilderGeneratorExtension = new Guid(BuilderGeneratorExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int BuildMenuGroup = 0x0001;
        public const int BuildCommand = 0x0100;
    }
}