// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BuilderGeneratorExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string BuilderGeneratorExtensionString = "3d97fea7-bb65-4102-8f8b-c184cc4fb4e4";
        public static Guid BuilderGeneratorExtension = new Guid(BuilderGeneratorExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int BuildMenuGroup = 0x0001;
        public const int BuildCommand = 0x0100;
    }
}